#-------------------------------
# Site Settings
title: LezBeHonest
logo: # You can add own logo. For example '/images/logo.png'.
description: A place where people are people and we do judge.

#-------------------------------
# Navigation Settings
menu-settings:
  menu-items:
    - title: 'Home'
      url: '/'
    - title: 'About'
      url: '/about/'

#-------------------------------
# Author Settings
author:
  name: Drake Reece
  avatar: '/images/Drake-Face.jpg'

#-------------------------------
# Hero Settings
hero:
  title: LezBeHonest
  description: A place where people are people and we do judge.
  image: '/images/index_bg.jpg'

#-------------------------------
# Footer section
social:
- {icon: "fa-brands fa-facebook-f", name: "Facebook", link: "https://www.facebook.com/TheDrake423"}
- {icon: "fa-brands fa-github", name: "Github", link: "https://github.com/DrakeReece/LezBeHonest.net/tree/main"}

#-------------------------------
# Google Analytics
google-analytics: G-DJXP9GESW9 # Add your identifier. For example UA-99631805-1.
